### ISSUE TITLE
Error Message with TCLChanger

### ISSUE THREAD

**Issue by theblindguidedog** [jacob-brown/TCLChanger#1]
<h1>Hi Jacob</h1> 
<p>I have been trying to use your TCLChanger but I keep getting the following error:</p>

<code>UnboundLocalError: local variable 'fileTCL' referenced before assignment</code>

<p>I have checked the spacing and it is all ok.</p>
<p>I done some Googling and it seems to be a problem with scope. I tried <code>global fileTCL</code> but that threw up another error.</p>
<p>Just thought I should let you know. I will continue to try to solve the issue myself and if I do I will get back to you.</p>

**Comment by theblindguidedog** [comment]
<p>I figured out why it wasn't working.
My <code>dist/test.app/Contents/Resources/tcl/init.tcl</code> didn't exist.</p>
<p>I copied init.tcl from somewhere else and created the location, your script then had no errors.</p>
<p>Unfortunately my app still doesn't work and I'm unsure why.</p><p>Any ideas?</p>

**Comment by cablecreek** [comment]
Hi,
After you added the new `init.tcl` what was your error message? 
Have you managed to use TCLChanger on a simple application? If you haven't perhaps give this a go.
